require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/support/**/*'
    - 'tmp/**/*'
Metrics/AbcSize:
  Exclude:
    - 'app/models/plantain/requests/aeon_external_request.rb'
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/plantain.rake'
    - 'app/controllers/catalog_controller.rb'
    - 'spec/jobs/index_job_spec.rb'
    - 'spec/features/traject/ead2_indexing_spec.rb'
    - 'config/routes.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/tasks/plantain.rake'
    - 'app/models/plantain/requests/aeon_external_request.rb'
    - 'lib/plantain/traject/ead2_config.rb'
Metrics/ExampleLength:
  Exclude:
    - 'spec/features/traject/ead2_indexing_spec.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/user_spec.rb'
