version: 2
jobs:
  build:
    working_directory: ~/plantain
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          RAILS_ENV: test
          PLANTAIN_DB_HOST: localhost
          PLANTAIN_DB_USERNAME: plantain
          PLANTAIN_DB_PASSWORD: ""
      - image: postgres:10
        environment:
          POSTGRES_USER: plantain
          POSTGRES_DB: plantain_test
          POSTGRES_PASSWORD: ""
      - image: solr:7.1-alpine
        command: bin/solr -cloud -noprompt -f -p 8984

    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: Set Timezone to EST/EDT
          command: echo 'America/New_York' = /etc/timezone
      # Restore bundle cache
      - restore_cache:
          keys:
            - plantain-{{ checksum "Gemfile.lock" }}
      - run: sudo apt update && sudo apt install postgresql-client
      - run:
          name: Update bundler
          command: |
            echo 'export BUNDLER_VERSION=2.0.2' >> $BASH_ENV
            gem install bundler -v 2.0.2
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: plantain-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      # project database settings
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rake db:migrate RAILS_ENV=test
      # Test
      - run:
          name: Run rubocop
          command: bundle exec rake rubocop
      - run:
          name: Run Rspec
          command: bundle exec rspec
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

      

      
