version: 2
jobs:
  build:
    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          RAILS_ENV: test
          PLANTAIN_DB_HOST: localhost
          PLANTAIN_DB_USERNAME: plantain
          PLANTAIN_DB_PASSWORD: ""
      - image: postgres:10
        environment:
          POSTGRES_USER: plantain
          POSTGRES_DB: plantain_test
          POSTGRES_PASSWORD: ""
      - image: solr:7.1-alpine
        command: bin/solr -cloud -noprompt -f -p 8984
    working_directory: ~/plantain
    steps:
      - checkout
      - run:
          name: Set Timezone to EST/EDT
          command: echo 'America/New_York' = /etc/timezone
      # Restore bundle cache
      - restore_cache:
          keys:
            - plantain-{{ checksum "Gemfile.lock" }}
      - run: sudo apt update && sudo apt install postgresql-client
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: plantain-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:setup
