version: 2
jobs:
  build:
    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
        environment:
          RAILS_ENV: test
          PULFA3_DB_HOST: localhost
          PULFA3_DB_USERNAME: pulfa3
          PULFA3_DB_PASSWORD: ""
      - image: postgres:10
        environment:
          POSTGRES_USER: pulfa3
          POSTGRES_DB: pulfa3_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/pulfa3-light
    steps:
      - checkout
      - run:
          name: Set Timezone to EST/EDT
          command: echo 'America/New_York' = /etc/timezone
      # Restore bundle cache
      - restore_cache:
          keys:
            - pulfa3-light-{{ checksum "Gemfile.lock" }}
            - pulfa3-light-
      - run: sudo apt update && sudo apt install postgresql-client
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: pulfa3-light-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:setup
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Start Solr test instance
          command: bundle exec rake pulfa:test
          background: true
      - run: bin/jetty_wait
      - run:
          name: Run RSpec
          command: bundle exec rspec spec

