--- # Please see the README for an overview of configuring citation formatting
eng: Technical and Scientific Reports, Engineering Library
lae: Latin American Ephemera Collections
selectors: Selectors
cotsen: Cotsen Children's Library, Department of Special Collections
mss: Manuscripts Division, Department of Special Collections
publicpolicy: Public Policy Papers, Department of Special Collections
univarchives: Princeton University Archives, Department of Special Collections
rarebooks: Rare Book Division, Department of Special Collections
ga: Graphic Arts Collection, Department of Special Collections
