# Use PostgreSQL for persistence in all environments
development: &default
  adapter: postgresql
  database: pulfa3_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 30)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  host: <%= ENV["PULFA3_DB_HOST"] %>
  database: pulfa3_test
  username: <%= ENV["PULFA3_DB_USERNAME"] %>
  password: <%= ENV["PULFA3_DB_PASSWORD"] %>

production: &deploy
  <<: *default
  adapter: postgresql
  host: <%= ENV["PULFA3_DB_HOST"] %>
  database: <%= ENV["PULFA3_DB"] %>
  username: <%= ENV["PULFA3_DB_USERNAME"] %>
  password: <%= ENV["PULFA3_DB_PASSWORD"] %>
  pool: 40

staging:
  <<: *deploy
