wa:
  name: 'Western Americana Collection'
  description: 'Western Americana Collection'
  building: 'Seeley G. Mudd Library'
  address1: 'Princeton University Library. Special Collections'
  address2: 'Manuscripts Division'
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: ''
  contact_info: '@princeton.edu'
  request_types:
    aeon_external_request_endpoint:
      request_url: 'https://lib-aeon.princeton.edu/aeon/testweb/Aeon.dll'
=begin
      {name: "Request", value: "32101037692462"}
      1: {name: "ItemSubTitle_32101037692462", value: "Boyd, Alice: Correspondence, 4 ALsS to Cosmo Monkhouse"}
      2: {name: "ItemTitle_32101037692462", value: "William Bell Scott Collection"}
      3: {name: "ItemAuthor_32101037692462", value: ""}
      4: {name: "ItemDate_32101037692462", value: "1890-1891"}
      5: {name: "ReferenceNumber_32101037692462", value: "C0959_c001"}
      6: {name: "CallNumber_32101037692462", value: "C0959"}
      7: {name: "ItemNumber_32101037692462", value: "32101037692462"}
      8: {name: "ItemVolume_32101037692462", value: "Box1"}
      9: {name: "Location_32101037692462", value: "mss"}
      10: {name: "ItemInfo1_32101037692462", value: "Collection is open for research use."}
      11: {name: "ItemInfo2_32101037692462", value: "0.2 linear feet | 1 half-size archival box"}
      12: {name: "ItemInfo3_32101037692462", value: " 1"}
      13: {name: "ItemInfo4_32101037692462", value: ","}
      14: {name: "ItemInfo5_32101037692462", value: "https://findingaids.princeton.edu/collections/C0959"}
=end
      request_mappings:
        static:
          Notes: ''
          scheduledDate: ''
          AeonForm: 'EADRequest'
          RequestType: 'Loan'
          GroupingIdentifier: 'ItemVolume'
          GroupingOption_ReferenceNumber: 'Concatenate'
          GroupingOption_ItemNumber: 'Concatenate'
          GroupingOption_ItemDate: 'FirstValue'
          GroupingOption_CallNumber: 'FirstValue'
          GroupingOption_ItemVolume: 'FirstValue'
          GroupingOption_ItemInfo1: 'FirstValue'
          GroupingOption_Location: 'FirstValue'
        accessor:
          DocumentType: document_type
          Site: site
          Location: location
          ItemTitle: title
nlm:
  name: 'National Library of Medicine. History of Medicine Division'
  description: 'NLM’s History of Medicine Division collects, preserves, makes available, and interprets for diverse audiences one of the world’s richest collections of historical material related to human health and disease.'
  building: 'Building 38, Room 1E-21'
  address1: '8600 Rockville Pike'
  address2: ''
  city: 'Bethesda'
  state: 'MD'
  zip: '20894'
  country: 'USA'
  phone: ''
  contact_info: 'hmdref@nlm.nih.gov'
  thumbnail_url: "https://collections.nlm.nih.gov/pageturnerserver/ajaxp?theurl=http://localhost:8080/fedora/get/nlm:nlmuid-101421040-img/THUMB"
  google_request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
  google_request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"
sul-spec:
  name: 'Stanford University Libraries. Special Collections and University Archives'
  visit_note: 'Special Collections and University Archives materials are stored offsite and must be paged 36 hours in advance.'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  building: 'Green Library'
  address1: '557 Escondido Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305'
  country: 'USA'
  phone: '(650) 725-1022'
  contact_info: 'specialcollections@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/collection/image/Collections-Super-Enlight.jpg'
umich-bhl:
  name: 'University of Michigan. Bentley Historical Library'
  description: 'The Bentley Historical Library collects the materials for and promotes the study of the histories of two great, intertwined institutions, the State of Michigan and the University of Michigan. The Library is open without fee to the public, and we welcome researchers regardless of academic or professional affiliation.'
  building: ''
  address1: '1150 Beal Ave'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109-2113'
  country: 'USA'
  phone: ''
  contact_info: 'bentley.ref@umich.edu'
  thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bhlexterior.jpg/150px-Bhlexterior.jpg'
