mudd:
  name: 'Seeley G. Mudd Manuscript Library'
  description: 'The Seeley G. Mudd Manuscript Library, a division of the Department of Rare Books and Special Collections, is a state-of-the-art repository constructed in 1976 to house the Princeton University Archives and a highly regarded collection of 20th-century public policy papers.'
  building: 'Seeley G. Mudd Manuscript Library'
  address1: '65 Olden Street'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-6345'
  contact_info: 'rbsc@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
mss:
  name: 'Manuscripts Division'
  description: 'Department of Rare Books and Special Collections'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-3184'
  contact_info: 'rbsc@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
cotsen:
  name: "Cotsen Children's Library"
  description: 'Department of Rare Books and Special Collections'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-3184'
  contact_info: 'rbsc@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
eng:
  name: "Engineering Library"
  description: 'The Engineering Library is located in Friend Center and supports the research and education mission of the School of Engineering and Applied Science and its affiliated programs and centers. The Library is part of the Collection Development Department of the Princeton University Library System and works closely with other library units and divisions to serve the needs of over 140 faculty, over 1200 undergraduate students and over 500 graduate students.'
  building: 'Friend Center'
  address1: ''
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '609-258-3200'
  contact_info: 'englib@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
rarebooks:
  name: "Rare Book Division"
  description: 'Department of Rare Books and Special Collections'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-3184'
  contact_info: 'rbsc@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
ga:
  name: "Graphic Arts Collection"
  description: 'Department of Rare Books and Special Collections'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-3184'
  contact_info: 'rbsc@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
lae:
  name: "Latin American Ephemera Collection"
  description: 'The Latin American Ephemera Collection contains thousands of digitized pamphlets, brochures, flyers, posters, placards and other printed items created since around the last quarter of the 20th century by a wide variety of social activists, non-governmental organizations, government agencies, political parties, public policy think tanks, and other types of organizations across Latin America, in order to publicize their views, positions, agendas, policies, events, and activities. The vast majority are rare, hard-to-find primary sources unavailable elsewhere.'
  building: 'Firestone Library'
  address1: 'Firestone Library B-14-P'
  address2: 'One Washington Road'
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '609-258-3193'
  contact_info: 'facosta@princeton.edu'
  thumbnail_url: ""
  google_request_url: ''
  google_request_mappings: ""
